server:
  port: 5454

spring:
  application:
    name: Online-Food-Ordering
  datasource:
    url: "jdbc:mysql://localhost:3308/online-food-order"
    driver: "com.mysql.cj.jdbc.Driver"
    username: root
    password: buicuong2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true

jwt:
  signerKey: "udsygfsduklgfukhgsiudfghfdshfyhg9ptyhfdhgfdguhfdgufhdfdghfdhgfdghfd"

payment:
  vnPay:
    url: ${PAY_URL}
    returnUrl: ${RETURN_URL}
    tmnCode: ${TMN_CODE}
    secretKey: ${SECRET_KEY}
    version: ${VERSION}
    command: ${COMMAND}
    orderType: ${ORDER_TYPE}
